<?php
namespace SclZfCartPayment\Method;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 00:29:05.
 */
class MethodLoaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MethodLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->serviceLocator = $this->getMock('Zend\ServiceManager\ServiceLocatorInterface');

        $this->object = new MethodLoader;

        $this->object->setServiceLocator($this->serviceLocator);
    }

    /**
     * @covers SclZfCartPayment\Method\MethodLoader::getMethod
     */
    public function testGetMethodWithGoodResult()
    {
        $methodName = 'TestMethod';

        $mockedMethod = $this->getMock('SclZfCartPayment\PaymentMethodInterface');

        $this->serviceLocator->expects($this->once())
            ->method('get')
            ->with($this->equalTo($methodName))
            ->will($this->returnValue($mockedMethod));

        $result = $this->object->getMethod($methodName);
        
        $this->assertEquals($mockedMethod, $result);
    }
}
