<?php
namespace SclZfCartPayment\Method;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 00:29:04.
 */
class MethodSelectorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MethodSelector
     */
    protected $object;

    /**
     * @var \Zend\Session\Container
     */
    protected $session;

    /**
     * @var \SclZfPayment\Method\MethodFetcherInterface
     */
    protected $fetcher;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->session = $this->getMockBuilder('Zend\Session\Container')
            ->disableOriginalConstructor()
            ->getMock();

        $this->fetcher = $this->getMock('SclZfCartPayment\Method\MethodFetcherInterface');

        $this->object = new MethodSelector($this->session, $this->fetcher);
    }

    /**
     * @covers SclZfCartPayment\Method\MethodSelector::setSelectedMethod
     * @todo   Implement testSetSelectedMethod().
     */
    public function testSetSelectedMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SclZfCartPayment\Method\MethodSelector::getSelectedMethod
     * @todo   Implement testGetSelectedMethod().
     */
    public function testGetSelectedMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
