<?php

namespace SclZfCartPaymentTests\Form;

use SclZfCartPayment\Form\PaymentMethods;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-15 at 19:15:04.
 */
class PaymentMethodsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PaymentMethods
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PaymentMethods;
    }

    /**
     * @covers SclZfCartPayment\Form\PaymentMethods::__construct
     */
    public function testConstruction()
    {
        $this->assertEquals('post', $this->object->getAttribute('method'));

        $submit = $this->object->get(PaymentMethods::ELEMENT_SUBMIT);
        $this->assertInstanceOf('Zend\Form\Element\Submit', $submit);
    }

    /**
     * @covers SclZfCartPayment\Form\PaymentMethods::addMethods
     * @todo   Check the radio values
     */
    public function testAddMethods()
    {
        $methods = array(
            'method1' => 'The Great Method',
            'method2' => 'Another Great Method',
        );

        $this->object->addMethods($methods);

        $element = $this->object->get(PaymentMethods::ELEMENT_METHOD);

        $this->assertInstanceOf('Zend\Form\Element\Radio', $element);
    }
}
