<?php
namespace SclZfCartPaymentTests\Method;

use SclZfCartPayment\Method\MethodLoader;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 00:29:05.
 */
class MethodLoaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MethodLoader
     */
    protected $object;

    /**
     *
     * @var Zend\ServiceManager\ServiceLocatorInterface
     */
    protected $serviceLocator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->serviceLocator = $this->getMock('Zend\ServiceManager\ServiceLocatorInterface');

        $this->object = new MethodLoader;

        $this->object->setServiceLocator($this->serviceLocator);
    }

    public function test_ServiceLocatorAwareInterface()
    {
        $newServiceLocator = $this->getMock('Zend\ServiceManager\ServiceLocatorInterface');
        $this->object->setServiceLocator($newServiceLocator);

        $this->assertEquals($newServiceLocator, $this->object->getServiceLocator());
    }

    public function test_getMethod_with_good_result()
    {
        $methodName = 'TestMethod';

        $mockedMethod = $this->getMock('SclZfCartPayment\PaymentMethodInterface');

        $this->serviceLocator->expects($this->once())
            ->method('get')
            ->with($this->equalTo($methodName))
            ->will($this->returnValue($mockedMethod));

        $result = $this->object->getMethod($methodName);

        $this->assertEquals($mockedMethod, $result);
    }

    public function test_getMethod_with_bad_result()
    {
        $methodName = 'TestMethod';

        $this->serviceLocator->expects($this->once())
            ->method('get')
            ->with($this->equalTo($methodName))
            ->will($this->returnValue('SomethingWrong'));

        $this->setExpectedException(
            'SclZfCartPayment\Exception\RuntimeException',
            'Expected instance of "SclZfCartPayment\PaymentMethodInterface"; got "string".'
        );

        $result = $this->object->getMethod($methodName);
    }
}
