<?php
namespace SclZfCartPayment\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 00:29:05.
 */
class MethodSelectorFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MethodSelectorFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MethodSelectorFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SclZfCartPayment\Service\MethodSelectorFactory::createService
     * @todo   Implement testCreateService().
     */
    public function testCreateService()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
